config/routes.rb
Storifire::Application.routes.draw do
  devise_for :users
  resources :steps
  resources :stories
  resources :roles
  resources :projects
  match 'stories/image/:id' => 'stories#yumlimg', :as => :yumlimg, via: [:get]
  match 'stories/role/:role' => 'stories#showRole', :as => :yumlroles, via: [:get]
  match 'stories/steps/:id' => 'stories#steps', :as => :steps_of, via: [:get]
  match 'stories/savetofile/' => 'stories#savetofile', :as => :savetofile, via: [:post]
  match 'roles/map/' => 'roles#map', :as => :roles_map, via: [:get]
  root :to => 'projects#index'
end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :role
	has_many :steps
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
#    Basecamp.establish_connection!('company.basecamphq.com', 'username', 'password', true)
#    me = Basecamp::Person.me
#    @user = me
    @stories = Story.includes(:role)
    @steps = Step.includes(:stories)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end
  def yumlimg
    @story = Story.find(params[:id])
  end


  # GET /stories/admin
  def showRole
    # @stories = Story.pluck(:role)
    @stories = Story.includes(:role)
  end
  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.all(:include => :role, :conditions => {:stories => { :id => params[:id] } })

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end
  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new
    @roles = Role.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  def savetofile
    @fileName = params[:path]
    @steps = Step.all(:include => :story, :conditions => {:steps => { :story_id => params[:story_id] } })
    @steps.each do |step|
      @doc = "#{step.kind} #{step.doer} #{step.verb} #{step.body}\n#{@doc}"
    end
    File.open(@fileName, 'w') {|f| f.write(@doc) }
    @result   = "success"
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
    @roles = Role.all
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end

  def steps
    @steps = Step.all(:include => :story, :conditions => {:steps => { :story_id => params[:id] } })
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
	def yuml_img(story)
		title = story.title
		"<img src='http://yuml.me/diagram/plain/usecase/[#{story.role.name}]-(#{title})' />".html_safe
	end

	def yuml_functions(stories)
		urlArg = ""
		stories.each do |story|
			urlArg << "[#{story.role.name}]-(#{story.title}),"
		end
		# urlArg << "[#{lastStory.role}]-(#{lastStory.title})"
		"<img src='http://yuml.me/diagram/plain/usecase/#{urlArg}' />".html_safe
	end
	def steps_of(story)
		"/stories/steps/#{story.id}"
	end
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
    <td>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    User role:<br />
    <select name='story[role_id]'>
      <% @roles.each do |role| %>
        <option value = <%= role.id %>> <%= role.name %></option>
      <% end %>
    </select>
  </div>
</td>
</tr>
<tr>
  <td>
    <div class="field">
      <%= f.label :points %><br />
      <%= f.number_field :points %>
    </div>
  </td>
</tr>
<tr>
  <td>
  <div style="float:left" class="field">
    <%= f.label :need %><br />
    <%= f.text_area :need %>
  </div>
  <div style="float:left" class="field">
    <%= f.label :goal %><br />
    <%= f.text_area :goal %>
  </div>
</td>
</tr>
<tr>
  <td>
  <div class="actions">
    <%= f.submit %>
  </div>
</td>
</tr>
<% end %>
</table>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h2>Listing stories</h2>
<!--Start stories loop -->
<%= link_to 'New Story', new_story_path %>
<hr />
<% @stories.each do |story| %>
<blockquote>
<h4>Story name: <%= story.title %></h4>
<script type='text/javascript'>
$(documemt).ready(function(){

});
</script>
<div class='options'>
	<%= link_to 'Edit', edit_story_path(story) %> |
	<%= link_to 'Destroy', story, confirm: 'Are you sure?', method: :delete %>|
	<%= link_to 'Image', yumlimg_path(story) %> |
	<%= link_to 'Role stories', yumlroles_path(story) %> |
	<%= link_to 'steps', steps_of_path(story) %>
</div>
<hr />
<blockquote><p>As <i><b><%= story.role.name %>,</b></i>
I'll <u><%= story.need %></u> so that I can <u><%= story.goal %></u>
</p>
</blockquote>
</blockquote>
<hr />
<% end %>
<hr />
<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/savetofile.html.erb
<% if @result %>
<span class="label label-success">File written successfully</span>
<% else %>
<span class="label label-important">Something went wrong!</span>
<% end %>
<br />
<%= link_to 'back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @story.first.title %></h1>

<p>As <i><b><%= @story.first.role.name %></b></i> <br />
I'll <u><%= @story.first.need %></u> so that I can <u><%= @story.first.goal %></u>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Destroy', @story, confirm: 'Are you sure?', method: :delete %> |
<%= link_to 'Back', stories_path %> |
<%= link_to 'Image', yumlimg_path(@story) %> |
<%= link_to 'Role stories', yumlroles_path(@story) %>

app/views/stories/showRole.html.erb
<%= yuml_functions @stories %>

app/views/stories/steps.html.erb
<pre>
<% @steps.each do |step| %>
<%= step.kind %> <%= step.doer %> <%= step.verb %> <%= step.body %>
<% end %>
</pre>
<form action='/stories/savetofile/' method='post'>
<input type='text' name='path' value="features/<%= @steps.first.story.title %>.feature" />
<input type='hidden' name='story_id' value="<%= @steps.first.story.id %>" />
<input type='submit' class="primary btn" value='save'/>

app/views/stories/yumlimg.html.erb
<%= yuml_img @story %>